global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.207.80.220:9100' , '10.207.80.116:9100' , '10.207.81.14:9100']

#  - job_name: 'nodeexporter'
#    scrape_interval: 5s
#    scrape_timeout: 5s
#    metrics_path: /metrics
#    scheme: http
#    dns_sd_configs:
#      - names:
#        - tasks.nodeexporter
#        refresh_interval: 30s
#        type: A
#        port: 9100

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.207.80.220:8080' , '10.207.80.116:8080' , '10.207.81.14:8080']

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.207.80.220:9090']

#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    honor_labels: true
#    static_configs:
#      - targets: ['pushgateway:9091']


alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['10.207.80.220:9093']

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
